@RaizesNordeste.Api_HostAddress = http://localhost:5216

POST {{RaizesNordeste.Api_HostAddress}}/api/usuarios
Content-Type: application/json

{
  "nome": "Cliente Teste",
  "email": "cliente.teste@raizes.local",
  "senha": "Teste@123"
}
###
