@RaizesNordeste.Api_HostAddress = https://localhost:7111

//Teste de criacao de cliente
POST {{RaizesNordeste.Api_HostAddress}}/api/usuarios
Content-Type: application/json

{
  "nome": "Cliente Teste",
  "email": "cliente.teste@raizes.local",
  "senha": "Teste@123"
}
###

//Teste de criacao de cliente 2
POST {{RaizesNordeste.Api_HostAddress}}/api/usuarios
Authorization: Bearer 
Content-Type: application/json

{
  "nome": "Cliente Teste2",
  "email": "cliente.teste@raizes2.local",
  "senha": "Teste2@123"
}
###

//Teste de login
###

POST {{RaizesNordeste.Api_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "cliente.teste@raizes.local",
  "senha": "Teste@123"
}


###

//Buscar usuários sem token
GET {{RaizesNordeste.Api_HostAddress}}/api/usuarios

###

// Buscar usuários como cliente
GET {{RaizesNordeste.Api_HostAddress}}/api/usuarios
Authorization: Bearer 
###

//  Login ADMIN
POST {{RaizesNordeste.Api_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "admin@raizes.local",
  "senha": "Admin@123"
}

###

// Buscar todos os usuários como ADMIN
GET {{RaizesNordeste.Api_HostAddress}}/api/usuarios
Authorization: Bearer 
###

// Buscar usuário existente por ID como ADMIN
GET {{RaizesNordeste.Api_HostAddress}}/api/usuarios/5
Authorization: Bearer 
###

//Buscar usuário inexistente como ADMIN
GET {{RaizesNordeste.Api_HostAddress}}/api/usuarios/999999
Authorization: Bearer 

###

### Listar unidades ativas
GET {{RaizesNordeste.Api_HostAddress}}/api/unidades
Accept: application/json

###

### Buscar unidade por ID
GET {{RaizesNordeste.Api_HostAddress}}/api/unidades/1
Accept: application/json

###

### Buscar unidade inexistente - esperado: 404
GET {{RaizesNordeste.Api_HostAddress}}/api/unidades/999999
Accept: application/json

###

### Buscar cardápio da unidade
GET {{RaizesNordeste.Api_HostAddress}}/api/unidades/1/cardapio
Accept: application/json

###

### Buscar cardápio de unidade inexistente - esperado: 404
GET {{RaizesNordeste.Api_HostAddress}}/api/unidades/999999/cardapio
Accept: application/json

###

