// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RaizesNordeste.Infrastructure.Persistence;

#nullable disable

namespace RaizesNordeste.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260923215043_SeedDadosIniciais")]
    partial class SeedDadosIniciais
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.Auditoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Detalhes")
                        .HasColumnType("text");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("RegistroId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Auditoria", (string)null);
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.Cardapio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<long>("CriadoPor")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UnidadeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPor");

                    b.HasIndex("UnidadeId")
                        .IsUnique();

                    b.ToTable("Cardapio", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Ativo = true,
                            CriadoPor = 1L,
                            DataCriacao = new DateTime(2026, 9, 22, 22, 3, 50, 0, DateTimeKind.Utc),
                            Nome = "Cardápio Recife",
                            UnidadeId = 1L
                        });
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.CardapioItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<long>("CardapioId")
                        .HasColumnType("bigint");

                    b.Property<long>("CriadoPor")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ProdutoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPor");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("CardapioId", "ProdutoId")
                        .IsUnique();

                    b.ToTable("CardapioItem", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Ativo = true,
                            CardapioId = 1L,
                            CriadoPor = 1L,
                            DataCriacao = new DateTime(2026, 9, 22, 22, 3, 50, 0, DateTimeKind.Utc),
                            ProdutoId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Ativo = true,
                            CardapioId = 1L,
                            CriadoPor = 1L,
                            DataCriacao = new DateTime(2026, 9, 22, 22, 3, 50, 0, DateTimeKind.Utc),
                            ProdutoId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            Ativo = true,
                            CardapioId = 1L,
                            CriadoPor = 1L,
                            DataCriacao = new DateTime(2026, 9, 22, 22, 3, 50, 0, DateTimeKind.Utc),
                            ProdutoId = 3L
                        },
                        new
                        {
                            Id = 4L,
                            Ativo = true,
                            CardapioId = 1L,
                            CriadoPor = 1L,
                            DataCriacao = new DateTime(2026, 9, 22, 22, 3, 50, 0, DateTimeKind.Utc),
                            ProdutoId = 4L
                        });
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.Consentimento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Aceito")
                        .HasColumnType("boolean");

                    b.Property<long>("CriadoPor")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TipoConsentimento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPor");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Consentimento", (string)null);
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.Estoque", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CriadoPor")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UnidadeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPor");

                    b.HasIndex("UnidadeId")
                        .IsUnique();

                    b.ToTable("Estoque", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CriadoPor = 1L,
                            DataCriacao = new DateTime(2026, 9, 22, 22, 3, 50, 0, DateTimeKind.Utc),
                            UnidadeId = 1L
                        });
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.ItemInventario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<long>("CriadoPor")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UnidadeMedida")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPor");

                    b.ToTable("ItemInventario", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Ativo = true,
                            CriadoPor = 1L,
                            DataCriacao = new DateTime(2026, 9, 22, 22, 3, 50, 0, DateTimeKind.Utc),
                            Nome = "Arroz",
                            Tipo = "Ingrediente",
                            UnidadeMedida = "g"
                        },
                        new
                        {
                            Id = 2L,
                            Ativo = true,
                            CriadoPor = 1L,
                            DataCriacao = new DateTime(2026, 9, 22, 22, 3, 50, 0, DateTimeKind.Utc),
                            Nome = "Feijão",
                            Tipo = "Ingrediente",
                            UnidadeMedida = "g"
                        },
                        new
                        {
                            Id = 3L,
                            Ativo = true,
                            CriadoPor = 1L,
                            DataCriacao = new DateTime(2026, 9, 22, 22, 3, 50, 0, DateTimeKind.Utc),
                            Nome = "Carne de Sol",
                            Tipo = "Ingrediente",
                            UnidadeMedida = "g"
                        },
                        new
                        {
                            Id = 4L,
                            Ativo = true,
                            CriadoPor = 1L,
                            DataCriacao = new DateTime(2026, 9, 22, 22, 3, 50, 0, DateTimeKind.Utc),
                            Nome = "Macaxeira",
                            Tipo = "Ingrediente",
                            UnidadeMedida = "g"
                        },
                        new
                        {
                            Id = 5L,
                            Ativo = true,
                            CriadoPor = 1L,
                            DataCriacao = new DateTime(2026, 9, 22, 22, 3, 50, 0, DateTimeKind.Utc),
                            Nome = "Flocão de Milho",
                            Tipo = "Ingrediente",
                            UnidadeMedida = "g"
                        },
                        new
                        {
                            Id = 6L,
                            Ativo = true,
                            CriadoPor = 1L,
                            DataCriacao = new DateTime(2026, 9, 22, 22, 3, 50, 0, DateTimeKind.Utc),
                            Nome = "Água Mineral",
                            Tipo = "Produto",
                            UnidadeMedida = "un"
                        });
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.Pagamento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CriadoPor")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdentificadorExterno")
                        .HasColumnType("text");

                    b.Property<long>("PedidoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Valor")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPor");

                    b.HasIndex("PedidoId");

                    b.ToTable("Pagamento", null, t =>
                        {
                            t.HasCheckConstraint("CK_Pagamento_Valor", "\"Valor\" >= 0");
                        });
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.Pedido", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CanalPedido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<long>("CriadoPor")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Desconto")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<long>("UnidadeId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("CriadoPor");

                    b.HasIndex("UnidadeId");

                    b.ToTable("Pedido", null, t =>
                        {
                            t.HasCheckConstraint("CK_Pedido_Desconto", "\"Desconto\" >= 0");

                            t.HasCheckConstraint("CK_Pedido_Subtotal", "\"Subtotal\" >= 0");

                            t.HasCheckConstraint("CK_Pedido_ValorTotal", "\"ValorTotal\" >= 0");
                        });
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.PedidoItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CriadoPor")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("PedidoId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProdutoId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("ValorUnitario")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPor");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("PedidoId", "ProdutoId")
                        .IsUnique();

                    b.ToTable("PedidoItem", null, t =>
                        {
                            t.HasCheckConstraint("CK_PedidoItem_Quantidade", "\"Quantidade\" > 0");

                            t.HasCheckConstraint("CK_PedidoItem_ValorTotal", "\"ValorTotal\" > 0");

                            t.HasCheckConstraint("CK_PedidoItem_ValorUnitario", "\"ValorUnitario\" > 0");
                        });
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.Perfil", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Perfil", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Descricao = "Perfil utilizado para operações automáticas dentro do sistema",
                            Nome = "Sistema"
                        },
                        new
                        {
                            Id = 2L,
                            Descricao = "Perfil com acesso admnistrativo do sistema",
                            Nome = "Administrador"
                        },
                        new
                        {
                            Id = 3L,
                            Descricao = "Perfil utilizado pelos funcionários de uma unidade dentro do sistema",
                            Nome = "Funcionário"
                        },
                        new
                        {
                            Id = 4L,
                            Descricao = "Perfil utilizado pelos clientes",
                            Nome = "Cliente"
                        });
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.PontosCliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<long>("CriadoPor")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Pontos")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .IsUnique();

                    b.HasIndex("CriadoPor");

                    b.ToTable("PontosCliente", (string)null);
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.PontosHistorico", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CriadoPor")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("PedidoId")
                        .HasColumnType("bigint");

                    b.Property<long>("PontosClienteId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<long?>("RegraResgateId")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoMovimentacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPor");

                    b.HasIndex("PedidoId");

                    b.HasIndex("PontosClienteId");

                    b.HasIndex("RegraResgateId");

                    b.ToTable("PontosHistorico", null, t =>
                        {
                            t.HasCheckConstraint("CK_PontosHistorico_Quantidade", "\"Quantidade\" > 0");
                        });
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.Produto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<long>("CriadoPor")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoProduto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ValorUnitario")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPor");

                    b.ToTable("Produto", null, t =>
                        {
                            t.HasCheckConstraint("CK_Produto_ValorUnitario", "\"ValorUnitario\" > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Ativo = true,
                            CriadoPor = 1L,
                            DataCriacao = new DateTime(2026, 9, 22, 22, 3, 50, 0, DateTimeKind.Utc),
                            Descricao = "Baião de dois tradicional",
                            Nome = "Baião de Dois",
                            TipoProduto = "Preparado",
                            ValorUnitario = 24.90m
                        },
                        new
                        {
                            Id = 2L,
                            Ativo = true,
                            CriadoPor = 1L,
                            DataCriacao = new DateTime(2026, 9, 22, 22, 3, 50, 0, DateTimeKind.Utc),
                            Descricao = "Carne de sol acompanhada de macaxeira",
                            Nome = "Carne de Sol com Macaxeira",
                            TipoProduto = "Preparado",
                            ValorUnitario = 34.90m
                        },
                        new
                        {
                            Id = 3L,
                            Ativo = true,
                            CriadoPor = 1L,
                            DataCriacao = new DateTime(2026, 9, 22, 22, 3, 50, 0, DateTimeKind.Utc),
                            Descricao = "Cuscuz tradicional nordestino",
                            Nome = "Cuscuz Nordestino",
                            TipoProduto = "Preparado",
                            ValorUnitario = 16.90m
                        },
                        new
                        {
                            Id = 4L,
                            Ativo = true,
                            CriadoPor = 1L,
                            DataCriacao = new DateTime(2026, 9, 22, 22, 3, 50, 0, DateTimeKind.Utc),
                            Descricao = "Água mineral sem gás",
                            Nome = "Água Mineral",
                            TipoProduto = "Unitario",
                            ValorUnitario = 5.00m
                        });
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.ProdutoItemInventario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CriadoPor")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ItemInventarioId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProdutoId")
                        .HasColumnType("bigint");

                    b.Property<int>("QuantidadeConsumo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPor");

                    b.HasIndex("ItemInventarioId");

                    b.HasIndex("ProdutoId", "ItemInventarioId")
                        .IsUnique();

                    b.ToTable("ProdutoItemInventario", null, t =>
                        {
                            t.HasCheckConstraint("CK_ProdutoItemInventario_QuantidadeConsumo", "\"QuantidadeConsumo\" > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CriadoPor = 1L,
                            DataCriacao = new DateTime(2026, 9, 22, 22, 3, 50, 0, DateTimeKind.Utc),
                            ItemInventarioId = 6L,
                            ProdutoId = 4L,
                            QuantidadeConsumo = 1
                        });
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.Receita", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CriadoPor")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ProdutoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPor");

                    b.HasIndex("ProdutoId")
                        .IsUnique();

                    b.ToTable("Receita", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CriadoPor = 1L,
                            DataCriacao = new DateTime(2026, 9, 22, 22, 3, 50, 0, DateTimeKind.Utc),
                            ProdutoId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            CriadoPor = 1L,
                            DataCriacao = new DateTime(2026, 9, 22, 22, 3, 50, 0, DateTimeKind.Utc),
                            ProdutoId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            CriadoPor = 1L,
                            DataCriacao = new DateTime(2026, 9, 22, 22, 3, 50, 0, DateTimeKind.Utc),
                            ProdutoId = 3L
                        });
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.ReceitaItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CriadoPor")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ItemInventarioId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<long>("ReceitaId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPor");

                    b.HasIndex("ReceitaId");

                    b.HasIndex("ItemInventarioId", "ReceitaId")
                        .IsUnique();

                    b.ToTable("ReceitaItem", null, t =>
                        {
                            t.HasCheckConstraint("CK_ReceitaItem_Quantidade", "\"Quantidade\" > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CriadoPor = 1L,
                            DataCriacao = new DateTime(2026, 9, 22, 22, 3, 50, 0, DateTimeKind.Utc),
                            ItemInventarioId = 1L,
                            Quantidade = 150,
                            ReceitaId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            CriadoPor = 1L,
                            DataCriacao = new DateTime(2026, 9, 22, 22, 3, 50, 0, DateTimeKind.Utc),
                            ItemInventarioId = 2L,
                            Quantidade = 100,
                            ReceitaId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            CriadoPor = 1L,
                            DataCriacao = new DateTime(2026, 9, 22, 22, 3, 50, 0, DateTimeKind.Utc),
                            ItemInventarioId = 3L,
                            Quantidade = 200,
                            ReceitaId = 2L
                        },
                        new
                        {
                            Id = 4L,
                            CriadoPor = 1L,
                            DataCriacao = new DateTime(2026, 9, 22, 22, 3, 50, 0, DateTimeKind.Utc),
                            ItemInventarioId = 4L,
                            Quantidade = 200,
                            ReceitaId = 2L
                        },
                        new
                        {
                            Id = 5L,
                            CriadoPor = 1L,
                            DataCriacao = new DateTime(2026, 9, 22, 22, 3, 50, 0, DateTimeKind.Utc),
                            ItemInventarioId = 5L,
                            Quantidade = 150,
                            ReceitaId = 3L
                        });
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.RegraResgatePontos", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<long>("CriadoPor")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PercentualDesconto")
                        .HasColumnType("integer");

                    b.Property<int>("PontosNecessarios")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPor");

                    b.ToTable("RegraResgatePontos", null, t =>
                        {
                            t.HasCheckConstraint("CK_RegraResgatePontos_PercentualDesconto", "\"PercentualDesconto\" > 0 AND \"PercentualDesconto\" <= 100");

                            t.HasCheckConstraint("CK_RegraResgatePontos_PontosNecessarios", "\"PontosNecessarios\" > 0");
                        });
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.SaldoEstoque", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CriadoPor")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("EstoqueId")
                        .HasColumnType("bigint");

                    b.Property<long>("ItemInventarioId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<int>("QuantidadeReservada")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPor");

                    b.HasIndex("EstoqueId");

                    b.HasIndex("ItemInventarioId", "EstoqueId")
                        .IsUnique();

                    b.ToTable("SaldoEstoque", null, t =>
                        {
                            t.HasCheckConstraint("CK_SaldoEstoque_Quantidade", "\"Quantidade\" >= 0");

                            t.HasCheckConstraint("CK_SaldoEstoque_QuantidadeReservada", "\"QuantidadeReservada\" >= 0 AND \"QuantidadeReservada\" <= \"Quantidade\"");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CriadoPor = 1L,
                            DataCriacao = new DateTime(2026, 9, 22, 22, 3, 50, 0, DateTimeKind.Utc),
                            EstoqueId = 1L,
                            ItemInventarioId = 1L,
                            Quantidade = 10000,
                            QuantidadeReservada = 0
                        },
                        new
                        {
                            Id = 2L,
                            CriadoPor = 1L,
                            DataCriacao = new DateTime(2026, 9, 22, 22, 3, 50, 0, DateTimeKind.Utc),
                            EstoqueId = 1L,
                            ItemInventarioId = 2L,
                            Quantidade = 10000,
                            QuantidadeReservada = 0
                        },
                        new
                        {
                            Id = 3L,
                            CriadoPor = 1L,
                            DataCriacao = new DateTime(2026, 9, 22, 22, 3, 50, 0, DateTimeKind.Utc),
                            EstoqueId = 1L,
                            ItemInventarioId = 3L,
                            Quantidade = 10000,
                            QuantidadeReservada = 0
                        },
                        new
                        {
                            Id = 4L,
                            CriadoPor = 1L,
                            DataCriacao = new DateTime(2026, 9, 22, 22, 3, 50, 0, DateTimeKind.Utc),
                            EstoqueId = 1L,
                            ItemInventarioId = 4L,
                            Quantidade = 10000,
                            QuantidadeReservada = 0
                        },
                        new
                        {
                            Id = 5L,
                            CriadoPor = 1L,
                            DataCriacao = new DateTime(2026, 9, 22, 22, 3, 50, 0, DateTimeKind.Utc),
                            EstoqueId = 1L,
                            ItemInventarioId = 5L,
                            Quantidade = 10000,
                            QuantidadeReservada = 0
                        },
                        new
                        {
                            Id = 6L,
                            CriadoPor = 1L,
                            DataCriacao = new DateTime(2026, 9, 22, 22, 3, 50, 0, DateTimeKind.Utc),
                            EstoqueId = 1L,
                            ItemInventarioId = 6L,
                            Quantidade = 20,
                            QuantidadeReservada = 0
                        });
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.Unidade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<long?>("CriadoPor")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPor");

                    b.ToTable("Unidade", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 9, 22, 22, 3, 50, 0, DateTimeKind.Utc),
                            Nome = "Raízes do Nordeste - Recife"
                        });
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<long?>("CriadoPor")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("PerfilId")
                        .HasColumnType("bigint");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Setor")
                        .HasColumnType("text");

                    b.Property<long?>("UnidadeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPor");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PerfilId");

                    b.HasIndex("UnidadeId");

                    b.ToTable("Usuario", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 9, 22, 22, 3, 50, 0, DateTimeKind.Utc),
                            Email = "sistema@raizes.local",
                            Nome = "Sistema",
                            PerfilId = 1L,
                            SenhaHash = "AQAAAAIAAYagAAAAEELYqfAH/8I1+eYUiig3UZ6Y8HIYlBAXboQowZcs5MUYtgFqPG6MX3MzEe8PLLVeuA=="
                        },
                        new
                        {
                            Id = 2L,
                            Ativo = true,
                            CriadoPor = 1L,
                            DataCriacao = new DateTime(2026, 9, 22, 22, 3, 50, 0, DateTimeKind.Utc),
                            Email = "admin@raizes.local",
                            Nome = "Administrador",
                            PerfilId = 2L,
                            SenhaHash = "AQAAAAIAAYagAAAAEHfNVxWoKHvZf17Kd1QRBwYzG0mHnVfsQc5YD9vOt0kzsc0bC1rd1PMzsN+NrlXp0w=="
                        },
                        new
                        {
                            Id = 3L,
                            Ativo = true,
                            CriadoPor = 1L,
                            DataCriacao = new DateTime(2026, 9, 22, 22, 3, 50, 0, DateTimeKind.Utc),
                            Email = "funcionario@raizes.local",
                            Nome = "Funcionário Atendimento",
                            PerfilId = 3L,
                            SenhaHash = "AQAAAAIAAYagAAAAEF89v0rZfLcKRzyyrtF5ta0Ni/9+rXPBUdagtzjp+Au7FPTCd1BfkFyAH7syokH9fw==",
                            Setor = "Atendimento",
                            UnidadeId = 1L
                        },
                        new
                        {
                            Id = 4L,
                            Ativo = true,
                            CriadoPor = 1L,
                            DataCriacao = new DateTime(2026, 9, 22, 22, 3, 50, 0, DateTimeKind.Utc),
                            Email = "cliente@raizes.local",
                            Nome = "Cliente Teste",
                            PerfilId = 4L,
                            SenhaHash = "AQAAAAIAAYagAAAAEDPlUNmZtkC3zUJ1RN4CubcAFyDUC69Mc/nXGqGwo7+0d9e3r1ELSXFuWfkZqeOWeA=="
                        });
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.Auditoria", b =>
                {
                    b.HasOne("RaizesNordeste.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Auditorias")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.Cardapio", b =>
                {
                    b.HasOne("RaizesNordeste.Domain.Entities.Usuario", "UsuarioCriador")
                        .WithMany()
                        .HasForeignKey("CriadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RaizesNordeste.Domain.Entities.Unidade", "Unidade")
                        .WithOne("Cardapio")
                        .HasForeignKey("RaizesNordeste.Domain.Entities.Cardapio", "UnidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Unidade");

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.CardapioItem", b =>
                {
                    b.HasOne("RaizesNordeste.Domain.Entities.Cardapio", "Cardapio")
                        .WithMany("Itens")
                        .HasForeignKey("CardapioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RaizesNordeste.Domain.Entities.Usuario", "UsuarioCriador")
                        .WithMany()
                        .HasForeignKey("CriadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RaizesNordeste.Domain.Entities.Produto", "Produto")
                        .WithMany("CardapiosItens")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cardapio");

                    b.Navigation("Produto");

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.Consentimento", b =>
                {
                    b.HasOne("RaizesNordeste.Domain.Entities.Usuario", "UsuarioCriador")
                        .WithMany()
                        .HasForeignKey("CriadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RaizesNordeste.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Consentimentos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.Estoque", b =>
                {
                    b.HasOne("RaizesNordeste.Domain.Entities.Usuario", "UsuarioCriador")
                        .WithMany()
                        .HasForeignKey("CriadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RaizesNordeste.Domain.Entities.Unidade", "Unidade")
                        .WithOne("Estoque")
                        .HasForeignKey("RaizesNordeste.Domain.Entities.Estoque", "UnidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Unidade");

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.ItemInventario", b =>
                {
                    b.HasOne("RaizesNordeste.Domain.Entities.Usuario", "UsuarioCriador")
                        .WithMany()
                        .HasForeignKey("CriadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.Pagamento", b =>
                {
                    b.HasOne("RaizesNordeste.Domain.Entities.Usuario", "UsuarioCriador")
                        .WithMany()
                        .HasForeignKey("CriadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RaizesNordeste.Domain.Entities.Pedido", "Pedido")
                        .WithMany("Pagamentos")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.Pedido", b =>
                {
                    b.HasOne("RaizesNordeste.Domain.Entities.Usuario", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RaizesNordeste.Domain.Entities.Usuario", "UsuarioCriador")
                        .WithMany()
                        .HasForeignKey("CriadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RaizesNordeste.Domain.Entities.Unidade", "Unidade")
                        .WithMany("Pedidos")
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Unidade");

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.PedidoItem", b =>
                {
                    b.HasOne("RaizesNordeste.Domain.Entities.Usuario", "UsuarioCriador")
                        .WithMany()
                        .HasForeignKey("CriadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RaizesNordeste.Domain.Entities.Pedido", "Pedido")
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RaizesNordeste.Domain.Entities.Produto", "Produto")
                        .WithMany("PedidosItens")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Produto");

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.PontosCliente", b =>
                {
                    b.HasOne("RaizesNordeste.Domain.Entities.Usuario", "Cliente")
                        .WithMany("PontosClientes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RaizesNordeste.Domain.Entities.Usuario", "UsuarioCriador")
                        .WithMany()
                        .HasForeignKey("CriadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.PontosHistorico", b =>
                {
                    b.HasOne("RaizesNordeste.Domain.Entities.Usuario", "UsuarioCriador")
                        .WithMany()
                        .HasForeignKey("CriadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RaizesNordeste.Domain.Entities.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RaizesNordeste.Domain.Entities.PontosCliente", "PontosCliente")
                        .WithMany("Historicos")
                        .HasForeignKey("PontosClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RaizesNordeste.Domain.Entities.RegraResgatePontos", "RegraResgatePontos")
                        .WithMany("Historicos")
                        .HasForeignKey("RegraResgateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Pedido");

                    b.Navigation("PontosCliente");

                    b.Navigation("RegraResgatePontos");

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.Produto", b =>
                {
                    b.HasOne("RaizesNordeste.Domain.Entities.Usuario", "UsuarioCriador")
                        .WithMany()
                        .HasForeignKey("CriadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.ProdutoItemInventario", b =>
                {
                    b.HasOne("RaizesNordeste.Domain.Entities.Usuario", "UsuarioCriador")
                        .WithMany()
                        .HasForeignKey("CriadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RaizesNordeste.Domain.Entities.ItemInventario", "ItemInventario")
                        .WithMany("ProdutosItens")
                        .HasForeignKey("ItemInventarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RaizesNordeste.Domain.Entities.Produto", "Produto")
                        .WithMany("ItensInventario")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemInventario");

                    b.Navigation("Produto");

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.Receita", b =>
                {
                    b.HasOne("RaizesNordeste.Domain.Entities.Usuario", "UsuarioCriador")
                        .WithMany()
                        .HasForeignKey("CriadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RaizesNordeste.Domain.Entities.Produto", "Produto")
                        .WithOne("Receita")
                        .HasForeignKey("RaizesNordeste.Domain.Entities.Receita", "ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.ReceitaItem", b =>
                {
                    b.HasOne("RaizesNordeste.Domain.Entities.Usuario", "UsuarioCriador")
                        .WithMany()
                        .HasForeignKey("CriadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RaizesNordeste.Domain.Entities.ItemInventario", "ItemInventario")
                        .WithMany("ReceitasItens")
                        .HasForeignKey("ItemInventarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RaizesNordeste.Domain.Entities.Receita", "Receita")
                        .WithMany("Itens")
                        .HasForeignKey("ReceitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemInventario");

                    b.Navigation("Receita");

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.RegraResgatePontos", b =>
                {
                    b.HasOne("RaizesNordeste.Domain.Entities.Usuario", "UsuarioCriador")
                        .WithMany()
                        .HasForeignKey("CriadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.SaldoEstoque", b =>
                {
                    b.HasOne("RaizesNordeste.Domain.Entities.Usuario", "UsuarioCriador")
                        .WithMany()
                        .HasForeignKey("CriadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RaizesNordeste.Domain.Entities.Estoque", "Estoque")
                        .WithMany("Saldos")
                        .HasForeignKey("EstoqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RaizesNordeste.Domain.Entities.ItemInventario", "ItemInventario")
                        .WithMany("SaldosEstoque")
                        .HasForeignKey("ItemInventarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estoque");

                    b.Navigation("ItemInventario");

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.Unidade", b =>
                {
                    b.HasOne("RaizesNordeste.Domain.Entities.Usuario", "UsuarioCriador")
                        .WithMany()
                        .HasForeignKey("CriadoPor")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("RaizesNordeste.Domain.Entities.Usuario", "UsuarioCriador")
                        .WithMany()
                        .HasForeignKey("CriadoPor")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RaizesNordeste.Domain.Entities.Perfil", "Perfil")
                        .WithMany("Usuarios")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RaizesNordeste.Domain.Entities.Unidade", "Unidade")
                        .WithMany("Usuarios")
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Perfil");

                    b.Navigation("Unidade");

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.Cardapio", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.Estoque", b =>
                {
                    b.Navigation("Saldos");
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.ItemInventario", b =>
                {
                    b.Navigation("ProdutosItens");

                    b.Navigation("ReceitasItens");

                    b.Navigation("SaldosEstoque");
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.Pedido", b =>
                {
                    b.Navigation("Itens");

                    b.Navigation("Pagamentos");
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.Perfil", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.PontosCliente", b =>
                {
                    b.Navigation("Historicos");
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.Produto", b =>
                {
                    b.Navigation("CardapiosItens");

                    b.Navigation("ItensInventario");

                    b.Navigation("PedidosItens");

                    b.Navigation("Receita");
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.Receita", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.RegraResgatePontos", b =>
                {
                    b.Navigation("Historicos");
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.Unidade", b =>
                {
                    b.Navigation("Cardapio")
                        .IsRequired();

                    b.Navigation("Estoque")
                        .IsRequired();

                    b.Navigation("Pedidos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Auditorias");

                    b.Navigation("Consentimentos");

                    b.Navigation("Pedidos");

                    b.Navigation("PontosClientes");
                });
#pragma warning restore 612, 618
        }
    }
}
