// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RaizesNordeste.Infrastructure.Persistence;

#nullable disable

namespace RaizesNordeste.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.Auditoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Detalhes")
                        .HasColumnType("text");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("RegistroId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Auditoria", (string)null);
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.Cardapio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<long>("CriadoPor")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UnidadeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPor");

                    b.HasIndex("UnidadeId")
                        .IsUnique();

                    b.ToTable("Cardapio", (string)null);
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.CardapioItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<long>("CardapioId")
                        .HasColumnType("bigint");

                    b.Property<long>("CriadoPor")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ProdutoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPor");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("CardapioId", "ProdutoId")
                        .IsUnique();

                    b.ToTable("CardapioItem", (string)null);
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.Consentimento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Aceito")
                        .HasColumnType("boolean");

                    b.Property<long>("CriadoPor")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TipoConsentimento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPor");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Consentimento", (string)null);
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.Estoque", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CriadoPor")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UnidadeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPor");

                    b.HasIndex("UnidadeId")
                        .IsUnique();

                    b.ToTable("Estoque", (string)null);
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.ItemInventario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<long>("CriadoPor")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UnidadeMedida")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPor");

                    b.ToTable("ItemInventario", (string)null);
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.Pagamento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CriadoPor")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdentificadorExterno")
                        .HasColumnType("text");

                    b.Property<long>("PedidoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Valor")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPor");

                    b.HasIndex("PedidoId");

                    b.ToTable("Pagamento", null, t =>
                        {
                            t.HasCheckConstraint("CK_Pagamento_Valor", "\"Valor\" >= 0");
                        });
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.Pedido", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CanalPedido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<long>("CriadoPor")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Desconto")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<long>("UnidadeId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("CriadoPor");

                    b.HasIndex("UnidadeId");

                    b.ToTable("Pedido", null, t =>
                        {
                            t.HasCheckConstraint("CK_Pedido_Desconto", "\"Desconto\" >= 0");

                            t.HasCheckConstraint("CK_Pedido_Subtotal", "\"Subtotal\" >= 0");

                            t.HasCheckConstraint("CK_Pedido_ValorTotal", "\"ValorTotal\" >= 0");
                        });
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.PedidoItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CriadoPor")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("PedidoId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProdutoId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("ValorUnitario")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPor");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("PedidoId", "ProdutoId")
                        .IsUnique();

                    b.ToTable("PedidoItem", null, t =>
                        {
                            t.HasCheckConstraint("CK_PedidoItem_Quantidade", "\"Quantidade\" > 0");

                            t.HasCheckConstraint("CK_PedidoItem_ValorTotal", "\"ValorTotal\" > 0");

                            t.HasCheckConstraint("CK_PedidoItem_ValorUnitario", "\"ValorUnitario\" > 0");
                        });
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.Perfil", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Perfil", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Descricao = "Perfil utilizado para operações automáticas dentro do sistema",
                            Nome = "Sistema"
                        },
                        new
                        {
                            Id = 2L,
                            Descricao = "Perfil com acesso admnistrativo do sistema",
                            Nome = "Administrador"
                        },
                        new
                        {
                            Id = 3L,
                            Descricao = "Perfil utilizado pelos funcionários de uma unidade dentro do sistema",
                            Nome = "Funcionário"
                        },
                        new
                        {
                            Id = 4L,
                            Descricao = "Perfil utilizado pelos clientes",
                            Nome = "Cliente"
                        });
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.PontosCliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<long>("CriadoPor")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Pontos")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .IsUnique();

                    b.HasIndex("CriadoPor");

                    b.ToTable("PontosCliente", (string)null);
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.PontosHistorico", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CriadoPor")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("PedidoId")
                        .HasColumnType("bigint");

                    b.Property<long>("PontosClienteId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<long?>("RegraResgateId")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoMovimentacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPor");

                    b.HasIndex("PedidoId");

                    b.HasIndex("PontosClienteId");

                    b.HasIndex("RegraResgateId");

                    b.ToTable("PontosHistorico", null, t =>
                        {
                            t.HasCheckConstraint("CK_PontosHistorico_Quantidade", "\"Quantidade\" > 0");
                        });
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.Produto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<long>("CriadoPor")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoProduto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ValorUnitario")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPor");

                    b.ToTable("Produto", null, t =>
                        {
                            t.HasCheckConstraint("CK_Produto_ValorUnitario", "\"ValorUnitario\" > 0");
                        });
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.ProdutoItemInventario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CriadoPor")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ItemInventarioId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProdutoId")
                        .HasColumnType("bigint");

                    b.Property<int>("QuantidadeConsumo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPor");

                    b.HasIndex("ItemInventarioId");

                    b.HasIndex("ProdutoId", "ItemInventarioId")
                        .IsUnique();

                    b.ToTable("ProdutoItemInventario", null, t =>
                        {
                            t.HasCheckConstraint("CK_ProdutoItemInventario_QuantidadeConsumo", "\"QuantidadeConsumo\" > 0");
                        });
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.Receita", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CriadoPor")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ProdutoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPor");

                    b.HasIndex("ProdutoId")
                        .IsUnique();

                    b.ToTable("Receita", (string)null);
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.ReceitaItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CriadoPor")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ItemInventarioId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<long>("ReceitaId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPor");

                    b.HasIndex("ReceitaId");

                    b.HasIndex("ItemInventarioId", "ReceitaId")
                        .IsUnique();

                    b.ToTable("ReceitaItem", null, t =>
                        {
                            t.HasCheckConstraint("CK_ReceitaItem_Quantidade", "\"Quantidade\" > 0");
                        });
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.RegraResgatePontos", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<long>("CriadoPor")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PercentualDesconto")
                        .HasColumnType("integer");

                    b.Property<int>("PontosNecessarios")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPor");

                    b.ToTable("RegraResgatePontos", null, t =>
                        {
                            t.HasCheckConstraint("CK_RegraResgatePontos_PercentualDesconto", "\"PercentualDesconto\" > 0 AND \"PercentualDesconto\" <= 100");

                            t.HasCheckConstraint("CK_RegraResgatePontos_PontosNecessarios", "\"PontosNecessarios\" > 0");
                        });
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.SaldoEstoque", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CriadoPor")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("EstoqueId")
                        .HasColumnType("bigint");

                    b.Property<long>("ItemInventarioId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<int>("QuantidadeReservada")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPor");

                    b.HasIndex("EstoqueId");

                    b.HasIndex("ItemInventarioId", "EstoqueId")
                        .IsUnique();

                    b.ToTable("SaldoEstoque", null, t =>
                        {
                            t.HasCheckConstraint("CK_SaldoEstoque_Quantidade", "\"Quantidade\" >= 0");

                            t.HasCheckConstraint("CK_SaldoEstoque_QuantidadeReservada", "\"QuantidadeReservada\" >= 0 AND \"QuantidadeReservada\" <= \"Quantidade\"");
                        });
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.Unidade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<long?>("CriadoPor")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPor");

                    b.ToTable("Unidade", (string)null);
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<long?>("CriadoPor")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("PerfilId")
                        .HasColumnType("bigint");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("UnidadeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPor");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PerfilId");

                    b.HasIndex("UnidadeId");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.Auditoria", b =>
                {
                    b.HasOne("RaizesNordeste.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Auditorias")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.Cardapio", b =>
                {
                    b.HasOne("RaizesNordeste.Domain.Entities.Usuario", "UsuarioCriador")
                        .WithMany()
                        .HasForeignKey("CriadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RaizesNordeste.Domain.Entities.Unidade", "Unidade")
                        .WithOne("Cardapio")
                        .HasForeignKey("RaizesNordeste.Domain.Entities.Cardapio", "UnidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Unidade");

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.CardapioItem", b =>
                {
                    b.HasOne("RaizesNordeste.Domain.Entities.Cardapio", "Cardapio")
                        .WithMany("Itens")
                        .HasForeignKey("CardapioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RaizesNordeste.Domain.Entities.Usuario", "UsuarioCriador")
                        .WithMany()
                        .HasForeignKey("CriadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RaizesNordeste.Domain.Entities.Produto", "Produto")
                        .WithMany("CardapiosItens")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cardapio");

                    b.Navigation("Produto");

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.Consentimento", b =>
                {
                    b.HasOne("RaizesNordeste.Domain.Entities.Usuario", "UsuarioCriador")
                        .WithMany()
                        .HasForeignKey("CriadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RaizesNordeste.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Consentimentos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.Estoque", b =>
                {
                    b.HasOne("RaizesNordeste.Domain.Entities.Usuario", "UsuarioCriador")
                        .WithMany()
                        .HasForeignKey("CriadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RaizesNordeste.Domain.Entities.Unidade", "Unidade")
                        .WithOne("Estoque")
                        .HasForeignKey("RaizesNordeste.Domain.Entities.Estoque", "UnidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Unidade");

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.ItemInventario", b =>
                {
                    b.HasOne("RaizesNordeste.Domain.Entities.Usuario", "UsuarioCriador")
                        .WithMany()
                        .HasForeignKey("CriadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.Pagamento", b =>
                {
                    b.HasOne("RaizesNordeste.Domain.Entities.Usuario", "UsuarioCriador")
                        .WithMany()
                        .HasForeignKey("CriadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RaizesNordeste.Domain.Entities.Pedido", "Pedido")
                        .WithMany("Pagamentos")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.Pedido", b =>
                {
                    b.HasOne("RaizesNordeste.Domain.Entities.Usuario", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RaizesNordeste.Domain.Entities.Usuario", "UsuarioCriador")
                        .WithMany()
                        .HasForeignKey("CriadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RaizesNordeste.Domain.Entities.Unidade", "Unidade")
                        .WithMany("Pedidos")
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Unidade");

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.PedidoItem", b =>
                {
                    b.HasOne("RaizesNordeste.Domain.Entities.Usuario", "UsuarioCriador")
                        .WithMany()
                        .HasForeignKey("CriadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RaizesNordeste.Domain.Entities.Pedido", "Pedido")
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RaizesNordeste.Domain.Entities.Produto", "Produto")
                        .WithMany("PedidosItens")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Produto");

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.PontosCliente", b =>
                {
                    b.HasOne("RaizesNordeste.Domain.Entities.Usuario", "Cliente")
                        .WithMany("PontosClientes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RaizesNordeste.Domain.Entities.Usuario", "UsuarioCriador")
                        .WithMany()
                        .HasForeignKey("CriadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.PontosHistorico", b =>
                {
                    b.HasOne("RaizesNordeste.Domain.Entities.Usuario", "UsuarioCriador")
                        .WithMany()
                        .HasForeignKey("CriadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RaizesNordeste.Domain.Entities.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RaizesNordeste.Domain.Entities.PontosCliente", "PontosCliente")
                        .WithMany("Historicos")
                        .HasForeignKey("PontosClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RaizesNordeste.Domain.Entities.RegraResgatePontos", "RegraResgatePontos")
                        .WithMany("Historicos")
                        .HasForeignKey("RegraResgateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Pedido");

                    b.Navigation("PontosCliente");

                    b.Navigation("RegraResgatePontos");

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.Produto", b =>
                {
                    b.HasOne("RaizesNordeste.Domain.Entities.Usuario", "UsuarioCriador")
                        .WithMany()
                        .HasForeignKey("CriadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.ProdutoItemInventario", b =>
                {
                    b.HasOne("RaizesNordeste.Domain.Entities.Usuario", "UsuarioCriador")
                        .WithMany()
                        .HasForeignKey("CriadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RaizesNordeste.Domain.Entities.ItemInventario", "ItemInventario")
                        .WithMany("ProdutosItens")
                        .HasForeignKey("ItemInventarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RaizesNordeste.Domain.Entities.Produto", "Produto")
                        .WithMany("ItensInventario")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemInventario");

                    b.Navigation("Produto");

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.Receita", b =>
                {
                    b.HasOne("RaizesNordeste.Domain.Entities.Usuario", "UsuarioCriador")
                        .WithMany()
                        .HasForeignKey("CriadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RaizesNordeste.Domain.Entities.Produto", "Produto")
                        .WithOne("Receita")
                        .HasForeignKey("RaizesNordeste.Domain.Entities.Receita", "ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.ReceitaItem", b =>
                {
                    b.HasOne("RaizesNordeste.Domain.Entities.Usuario", "UsuarioCriador")
                        .WithMany()
                        .HasForeignKey("CriadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RaizesNordeste.Domain.Entities.ItemInventario", "ItemInventario")
                        .WithMany("ReceitasItens")
                        .HasForeignKey("ItemInventarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RaizesNordeste.Domain.Entities.Receita", "Receita")
                        .WithMany("Itens")
                        .HasForeignKey("ReceitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemInventario");

                    b.Navigation("Receita");

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.RegraResgatePontos", b =>
                {
                    b.HasOne("RaizesNordeste.Domain.Entities.Usuario", "UsuarioCriador")
                        .WithMany()
                        .HasForeignKey("CriadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.SaldoEstoque", b =>
                {
                    b.HasOne("RaizesNordeste.Domain.Entities.Usuario", "UsuarioCriador")
                        .WithMany()
                        .HasForeignKey("CriadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RaizesNordeste.Domain.Entities.Estoque", "Estoque")
                        .WithMany("Saldos")
                        .HasForeignKey("EstoqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RaizesNordeste.Domain.Entities.ItemInventario", "ItemInventario")
                        .WithMany("SaldosEstoque")
                        .HasForeignKey("ItemInventarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estoque");

                    b.Navigation("ItemInventario");

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.Unidade", b =>
                {
                    b.HasOne("RaizesNordeste.Domain.Entities.Usuario", "UsuarioCriador")
                        .WithMany()
                        .HasForeignKey("CriadoPor")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("RaizesNordeste.Domain.Entities.Usuario", "UsuarioCriador")
                        .WithMany()
                        .HasForeignKey("CriadoPor")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RaizesNordeste.Domain.Entities.Perfil", "Perfil")
                        .WithMany("Usuarios")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RaizesNordeste.Domain.Entities.Unidade", "Unidade")
                        .WithMany("Usuarios")
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Perfil");

                    b.Navigation("Unidade");

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.Cardapio", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.Estoque", b =>
                {
                    b.Navigation("Saldos");
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.ItemInventario", b =>
                {
                    b.Navigation("ProdutosItens");

                    b.Navigation("ReceitasItens");

                    b.Navigation("SaldosEstoque");
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.Pedido", b =>
                {
                    b.Navigation("Itens");

                    b.Navigation("Pagamentos");
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.Perfil", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.PontosCliente", b =>
                {
                    b.Navigation("Historicos");
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.Produto", b =>
                {
                    b.Navigation("CardapiosItens");

                    b.Navigation("ItensInventario");

                    b.Navigation("PedidosItens");

                    b.Navigation("Receita");
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.Receita", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.RegraResgatePontos", b =>
                {
                    b.Navigation("Historicos");
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.Unidade", b =>
                {
                    b.Navigation("Cardapio")
                        .IsRequired();

                    b.Navigation("Estoque")
                        .IsRequired();

                    b.Navigation("Pedidos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("RaizesNordeste.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Auditorias");

                    b.Navigation("Consentimentos");

                    b.Navigation("Pedidos");

                    b.Navigation("PontosClientes");
                });
#pragma warning restore 612, 618
        }
    }
}
